development:
  adapter: mysql
  database: turkopticon_development
  host: localhost
  username: devel_user
  password: devel_pass

production:
  adapter: mysql
  database: turkopticon_production
  host: localhost
  username: production_user
  password: production_pass
